version: "3.4"
services:
    postgres-statutory:
        restart: always
        image: postgres:10.18
        volumes:
            - postgres-statutory:/var/lib/postgresql/data
        expose:
            - "5432"
        environment:
            POSTGRES_USER: "postgres"
            POSTGRES_PASSWORD: "${PW_POSTGRES}"
        labels:
            # we don't access via traefik
            - "traefik.enable=false"

    statutory:
        restart: always
        image: aegee/statutory:latest
        volumes:
            - statutory-media:/usr/app/media
            - shared:/usr/app/shared:ro
        depends_on:
            - postgres-statutory
        expose:
            - "8084"
        environment:
            BUGSNAG_KEY: "${BUGSNAG_KEY_STATUTORY}"
            PG_PASSWORD: "${PW_POSTGRES}"
            NODE_ENV: "${MYAEGEE_ENV}"
            HOST: "${SUBDOMAIN_FRONTEND}${BASE_URL}"
            CORE_LOGIN: "${CORE_LOGIN}"
            CORE_PASSWORD: "${CORE_PASSWORD}"
        healthcheck:
            test: ["CMD", "curl", "-f", "http://localhost:8084/healthcheck"]
            interval: 30s
            timeout: 10s
            retries: 3
            start_period: 40s
        # cpu_count: 1
        # mem_limit: 900m
        labels:
            - "traefik.enable=true"
            - "traefik.http.routers.statutory.entrypoints=websecure"
            - "traefik.http.routers.statutory.tls=true"
            - "traefik.http.routers.statutory.rule=Host(`${SUBDOMAIN_FRONTEND}${BASE_URL}`) && PathPrefix(`/api/statutory`)"

            - "traefik.http.routers.statutory.middlewares=statutory-stripprefix"
            - "traefik.http.middlewares.statutory-stripprefix.stripprefix.prefixes=/api/statutory"

            - "traefik.http.routers.statutory-metrics.rule=Host(`${SUBDOMAIN_FRONTEND}${BASE_URL}`) && PathPrefix(`/api/statutory/metrics`)"
            - "traefik.http.routers.statutory-metrics.middlewares=statutory-stripprefix, metricsauth"

    statutory-static:
        restart: on-failure
        image: aegee/nginx-static:prod
        volumes:
            - statutory-media:/usr/app/media:ro
            - shared:/usr/app/shared:ro
        expose:
            - "80"
        healthcheck:
            test: ["CMD", "curl", "-f", "http://localhost:80/healthcheck"]
            interval: 30s
            timeout: 10s
            retries: 3
            start_period: 40s
        labels:
            - "traefik.enable=true"
            - "traefik.http.routers.statutory-static.entrypoints=websecure"
            - "traefik.http.routers.statutory-static.rule=PathPrefix(`/media/statutory`)"
            - "traefik.http.routers.statutory-static.middlewares=statutory-static-stripprefix"
            - "traefik.http.middlewares.statutory-static-stripprefix.stripprefix.prefixes=/media/statutory"

volumes:
    postgres-statutory:
        driver: local
    statutory-media:
        driver: local
    shared:
        driver: local

networks:
    default:
        external:
            name: OMS
