FROM nginx:alpine

RUN rm /etc/nginx/conf.d/default.conf 
    
RUN mkdir -p /usr/app/ \
        && mkdir -p /usr/app/frontend \
        && mkdir -p /usr/app/media \
        && mkdir -p /usr/scripts \
        && mkdir -p /usr/shared
        
WORKDIR /usr/app


ADD ./nginx.conf /etc/nginx/
COPY ./sites/*.conf /etc/nginx/sites-available/

CMD ["nginx"]

EXPOSE 8083
