version: "3.4"

services:
    frontend:
        restart: always
        image: aegee/frontend:latest
        # Healthcheck is disabled because traefik doesn't route stuff to the service
        # unless it's healthy, causing the ~1min downtime for frontend
        # while it waits for the container to be up.
        # healthcheck:
        #     test: ["CMD", "curl", "--fail", "http://localhost/healthcheck"]
        #     interval: 30s
        #     timeout: 10s
        #     retries: 3
        # cpu_count: 1
        # mem_limit: 900m
        labels:
          - "traefik.http.routers.frontend.rule=Host(`${SUBDOMAIN_FRONTEND}${BASE_URL}`)"
          - "traefik.http.routers.frontend.tls=true"

networks:
    default:
        external:
            name: OMS
