version: 2
updates:
  # Git submodules
  - package-ecosystem: "gitsubmodule"
    directory: "/"
    schedule:
      interval: daily
    open-pull-requests-limit: 99
    reviewers:
      - "WikiRik"

  # NPM dependencies across all workspaces
  - package-ecosystem: "npm"
    directories:
      - "/"
      - "/core"
      - "/events"
      - "/frontend"
      - "/discounts"
      - "/knowledge"
      - "/network"
      - "/statutory"
      - "/summeruniversity"
      - "/mailer"
    schedule:
      interval: "weekly"
      day: "friday"
    open-pull-requests-limit: 99
    reviewers:
      - "WikiRik"

  # Docker images across all modules
  - package-ecosystem: "docker"
    directories:
      - "/core/docker/core"
      - "/discounts/docker/discounts"
      - "/events/docker/events"
      - "/frontend/docker"
      - "/knowledge/docker/knowledge"
      - "/mailer/docker/mailer"
      - "/mailer/docker/mail_transfer_agent"
      - "/network/docker/network"
      - "/statutory/docker/statutory"
      - "/summeruniversity/docker/summeruniversity"
      - "/gateways/docker/portal"
      - "/monitor/docker/logstash"
    schedule:
      interval: "weekly"
      day: "friday"
    open-pull-requests-limit: 99
    reviewers:
      - "WikiRik"

  # GitHub Actions across all modules
  - package-ecosystem: "github-actions"
    directories:
      - "/core"
      - "/discounts"
      - "/events"
      - "/frontend"
      - "/knowledge"
      - "/network"
      - "/statutory"
      - "/summeruniversity"
    schedule:
      interval: "weekly"
      day: "friday"
    open-pull-requests-limit: 99
    reviewers:
      - "WikiRik"
