global:
  checkNewVersion: true
  sendAnonymousUsage: false
entryPoints:
  http:
    address: :80
providers:
  providersThrottleDuration: 2s
  docker:
    watch: true
    endpoint: unix:///var/run/docker.sock
    useBindPortIP: true
    swarmModeRefreshSeconds: 15s
  file: {}
log:
  level: INFO
accessLog: {}
