language: shell
dist: trusty
sudo: required
git:
  depth: 3

services:
  - docker

script:
    - bash ./oms.sh build --no-cache
    - bash ./oms.sh up -d
    - sleep 120
    - bash ./oms.sh logs
    - bash ./oms.sh ps
    - bash ./oms.sh exec -T -d traefik help 2>/dev/null || exit 1
    - bash ./oms.sh exec -T -d postgres-oms-core-elixir true 2>/dev/null || exit 1
    - bash ./oms.sh exec -T -d pgadmin true 2>/dev/null || exit 1
    - bash ./oms.sh exec -T -d oms-core-elixir true 2>/dev/null || exit 1
    - bash ./oms.sh exec -T -d oms-events true 2>/dev/null || exit 1
    - bash ./oms.sh exec -T -d mongodb true 2>/dev/null || exit 1
    - bash ./oms.sh exec -T -d omsserviceregistry true 2>/dev/null || exit 1
    - bash ./tests/LocalLoopbackTest/LocalLoopbackTest.sh
