language: shell
dist: trusty
sudo: required

services:
  - docker

script:
    - bash ./oms.sh --build --down_v
    - sleep 120
    - cd docker
    - docker-compose logs
    - docker-compose exec -T -d traefik help 2>/dev/null || exit 1
    - cd ../oms-core/docker
    - docker-compose logs
    - docker-compose exec -T -d omscore true 2>/dev/null || exit 1
    - docker-compose exec -T -d php-fpm true 2>/dev/null || exit 1
    - docker-compose exec -T -d omscore-nginx true 2>/dev/null || exit 1
    - docker-compose exec -T -d postgres true 2>/dev/null || exit 1
    - docker-compose exec -T -d pgadmin true 2>/dev/null || exit 1
    - docker-compose exec -T omscore ./vendor/bin/phpunit
    - cd ../../
    - cd ./tests/LocalLoopbackTest
    - sudo bash ./LocalLoopbackTest.sh
