language: shell
dist: xenial
sudo: required
git:
  depth: 3

services:
  - docker

script:
    - bash ./vagrant-post-script/generate_secrets.sh
    - bash ./helper.sh -v --init
    - bash ./helper.sh -v --build
    - bash ./helper.sh --start
    - sleep 60
    - bash ./helper.sh --execute -- -T -d traefik help 2>/dev/null 
    - bash ./helper.sh --execute -- -T -d oms-frontend true 2>/dev/null 
