language: shell
dist: trusty
sudo: required

before_install:
    - sudo apt-get update
    - sudo apt-get install apt-transport-https ca-certificates curl software-properties-common
    - curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
    - sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"
    - sudo apt-get update || true
    - sudo apt-get install docker-ce
    - sudo docker run hello-world


before_script:
    - cd docker


script:
    - sudo bash ./oms_setup.sh
    - docker-compose up -d
    - docker-compose logs
    - sleep 60
    - sudo docker-compose exec -T traefik true 2>/dev/null || exit 1
    - sudo docker-compose exec -T omscore true 2>/dev/null || exit 1
    - sudo docker-compose exec -T php-fpm true 2>/dev/null || exit 1
    - sudo docker-compose exec -T omscore-nginx true 2>/dev/null || exit 1
    - sudo docker-compose exec -T postgres true 2>/dev/null || exit 1
    - sudo docker-compose exec -T pgadmin true 2>/dev/null || exit 1
    - sudo docker-compose exec -T omscore composer install
    - sudo docker-compose exec -T omscore php artisan key:generate
    - sudo docker-compose exec -T omscore php artisan config:cache
    - sudo docker-compose exec -T omscore php artisan migrate:refresh --seed
    - sudo docker-compose exec -T omscore ./vendor/bin/phpunit
