language: shell
dist: trusty
sudo: required
git:
  depth: 3

services:
  - docker

script:
    - bash ./helper.sh -v --init
    - bash ./helper.sh -v --build
    - bash ./helper.sh --start
    - sleep 60
    - bash ./helper.sh --exec -- -T -d traefik help 2>/dev/null 
    - bash ./helper.sh --exec -- -T -d oms-frontend true 2>/dev/null 
