language: shell
dist: trusty
sudo: required

before_install:
    - sudo apt-get update
    - sudo apt-get install apt-transport-https ca-certificates curl software-properties-common
    - curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
    - sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"
    - sudo apt-get update || true
    - sudo apt-get install docker-ce
    - sudo docker run hello-world


#before_script:
#    - cd docker


script:
    - sudo bash ./oms_setup.sh
    - ./docker-compose.sh up -d
    - sleep 60
    - ./docker-compose.sh logs
    - sudo ./docker-compose.sh exec -T -d traefik help 2>/dev/null || exit 1
    - sudo ./docker-compose.sh exec -T -d omscore true 2>/dev/null || exit 1
    - sudo ./docker-compose.sh exec -T -d php-fpm true 2>/dev/null || exit 1
    - sudo ./docker-compose.sh exec -T -d omscore-nginx true 2>/dev/null || exit 1
    - sudo ./docker-compose.sh exec -T -d postgres true 2>/dev/null || exit 1
    - sudo ./docker-compose.sh exec -T -d pgadmin true 2>/dev/null || exit 1
    - sudo ./docker-compose.sh exec -T omscore composer install
    - sudo ./docker-compose.sh exec -T omscore php artisan key:generate
    - sudo ./docker-compose.sh exec -T omscore php artisan config:cache
    - sudo ./docker-compose.sh exec -T omscore php artisan migrate:refresh --seed
    - sudo ./docker-compose.sh exec -T omscore ./vendor/bin/phpunit
    - cd ./tests/LocalLoopbackTest
    - sudo bash ./LocalLoopbackTest.sh
