language: shell
dist: trusty
sudo: required

services:
  - docker

script:
    - bash ./oms.sh up -d --build
    - sleep 120
    - bash ./oms.sh logs
    - bash ./oms.sh exec -T -d traefik help 2>/dev/null || exit 1
    - bash ./oms.sh exec -T -d omscore true 2>/dev/null || exit 1
    - bash ./oms.sh exec -T -d php-fpm true 2>/dev/null || exit 1
    - bash ./oms.sh exec -T -d omscore-nginx true 2>/dev/null || exit 1
    - bash ./oms.sh exec -T -d postgres true 2>/dev/null || exit 1
    - bash ./oms.sh exec -T -d pgadmin true 2>/dev/null || exit 1
    - bash ./oms.sh exec -T omscore ./vendor/bin/phpunit
    - sudo bash ./tests/LocalLoopbackTest.sh
