version: '3.2'

secrets:
    jwt_key:
        file: secrets/jwt_key
    sendgrid_key:
        file: secrets/sendgrid_key
    https_cert:
        file: secrets/cert.pem
    https_key:
        file: secrets/key.pem
