version: "3.4"

#TODO make sure all services always have the appropriate
#       restart: on-failure
#TODO: maybe add also the web interfaces for postgre, mongo, whichever?
services:

### OMS TUNNEL        #######################################
### Proxy container #######################################

    traefik:
        image: traefik:v1.7.4-alpine
        restart: always
        command: --web.metrics.prometheus
        ports:
          - 80:80
          - 443:443
        volumes:
          - /var/run/docker.sock:/var/run/docker.sock:ro
          - ./secrets/acme.json:/etc/acme.json #we have to mount it to preserve it on the host, so no secrets
          - ./${PATH_OMS_GLOBAL}/traefik/traefik.toml:/etc/traefik/traefik.toml
          - ./${PATH_OMS_GLOBAL}/traefik/logs:/var/log/traefik/
          #- shared_logs:/var/log/traefik/
#        networks:
#          - management
        labels:
          - traefik.enable=true
          - traefik.backend=traefik
          - traefik.port=8080
          - traefik.frontend.rule=Host:${SUBDOMAIN_TRAEFIK}${BASE_URL}
          - traefik.frontend.priority=20
          - traefik.frontend.auth.basic.users=admin:${PW_TRAEFIK}

    portal:
        restart: on-failure
        build:
          context: ./$PATH_OMS_GLOBAL/portal/
          dockerfile: ./Dockerfile.dev
        image: aegee/portal:dev
        restart: always
        expose:
          - 80
        labels:
          - traefik.enable=true
          - traefik.backend=portal
          - traefik.port=80
          - traefik.frontend.rule=Host:${SUBDOMAIN_PORTAL}${BASE_URL}
          - traefik.frontend.priority=20

### DB admin (UIs) Containers #######################################

### pgAdmin Container #######################################

    pgadmin:
        image: fenglc/pgadmin4:2.0
        restart: on-failure
        expose:
            - 5050
        labels:
          - traefik.enable=true
          - traefik.backend=pgadmin
          - traefik.port=5050
          - traefik.frontend.rule=Host:${SUBDOMAIN_PGADMIN}${BASE_URL}
          - traefik.frontend.priority=20
          - traefik.frontend.auth.basic.users=admin:${PW_PGADMIN_BLOWF}
        environment:
          DEFAULT_USER: admin@aegee.org
          DEFAULT_PASSWORD: ${PW_PGADMIN}

### mongoui Container #######################################
    # mongoui:
    #     build:
    #        context: ./oms-util/docker/mongoui
    #        dockerfile: ./Dockerfile.dev
    #     expose:
    #         - 3000
    #     labels:
    #       - traefik.enable=true
    #       - traefik.backend=mongoui
    #       - traefik.port=3000
    #       - traefik.frontend.rule=Host:${SUBDOMAIN_MONGOADMIN}${BASE_URL}
    #       - traefik.frontend.priority=20
    #       - traefik.frontend.auth.basic.users=admin:${PW_MONGO_BLOWF}


#volumes:
#   shared_logs:
#       driver: "local"
#   upload:


networks:
  default:
    external:
      name: OMS
