FROM node:8

WORKDIR /
RUN git clone https://github.com/mrvautin/adminMongo.git \
    && cd adminMongo \
    && npm i \
    && npm cache clean --force
    
COPY ./app.json /adminMongo/config/app.json
COPY ./config.json /adminMongo/config/config.json

WORKDIR /adminMongo

CMD npm start

EXPOSE 3000
