---
nodejs_version: "16.20.2"
nodejs_version_output: "v{{ nodejs_version }}"
npm_version: "9.6.4"

python_version: "3.10.3"

docker_version: "19.03.1"
docker_ubuntu_version: "5:{{ docker_version }}~3-0~ubuntu-bionic"
docker_compose_version: "1.24.0"
docker_users: ["vagrant"]

packages_to_install: [ 'make', 'jq', 'net-tools', 'vim', 'sqlite3', 'cowsay', 'figlet']
