version: "3.4"

services:
    mailer:
        restart: unless-stopped
        image: aegee/mailer:latest
        expose:
            - "4000"
        environment:
            MIX_ENV: "${MYAEGEE_ENV}"
            SMTP_USER: ${SMTP_USER?The SMTP_USER variable is not set.}
        depends_on:
            - mail-transfer-agent
        healthcheck:
            test: ["CMD", "curl", "-f", "http://localhost:4000/healthcheck"]
            interval: 30s
            timeout: 10s
            retries: 3
            start_period: 40s
        # Only exposing /healthcheck endpoint
        labels:
            - "traefik.enable=true"
            - "traefik.http.routers.mailer.rule=PathPrefix(`/api/mailer/healthcheck`)"
            - "traefik.http.routers.mailer.middlewares=mailer-stripprefix"
            - "traefik.http.middlewares.mailer-stripprefix.stripprefix.prefixes=/api/mailer"
        # cpu_count: 1
        # mem_limit: 900m

    mail-transfer-agent:
        restart: always
        image: aegee/mail-transfer-agent:latest
        expose:
            - "25"
        environment:
            SMTP_HOST: ${SMTP_HOST?The SMTP_HOST variable is not set.}
            SMTP_PORT: 587
            SMTP_USER: ${SMTP_USER?The SMTP_USER variable is not set.}
            SMTP_PASSWORD: ${SMTP_PASSWORD?The SMTP_PASSWORD variable is not set.}
        #healthcheck?
        # cpu_count: 1
        # mem_limit: 900m

networks:
    default:
        external:
            name: OMS
