version: "3.4"

services:

### container administration helper Container #######################################
  # This is not meant to use in prod! only in local env for newbies
  # To get the password (hashed): (also remember to escape $ with another $)
  #   docker run --rm httpd:2.4-alpine htpasswd -nbB admin 5ecr3t | cut -d ":" -f 2
  portainer:
    restart: "no"
    image: portainer/portainer:1.25.0
    # image: portainer/portainer-ce:2.15.0
    command: -H unix:///var/run/docker.sock --admin-password ${PW_TRAEFIK} --logo ${AEGEE_LOGO_B64}  # yamllint disable-line rule:line-length
    expose:
      - "9000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:rw
      # - portainer-data:/data
    labels:
      - "traefik.enable=true"
      - "traefik.backend=portainer"
      - "traefik.port=9000"
      - "traefik.frontend.rule=Host:${SUBDOMAIN_PORTAINER}${BASE_URL}"
      - "traefik.frontend.priority=20"

### DB admin (UIs) Containers #######################################

### pg Admin Container #######################################
  pgadmin:
    image: dpage/pgadmin4:4.23
    restart: on-failure
    expose:
      - "5050"
    labels:
      - "traefik.enable=true"
      - "traefik.backend=pgadmin"
      - "traefik.port=5050"
      - "traefik.frontend.rule=Host:${SUBDOMAIN_PGADMIN}${BASE_URL}"
      - "traefik.frontend.priority=20"
      - "traefik.frontend.auth.basic.users=admin:${PW_TRAEFIK}"
    environment:
      PGADMIN_DEFAULT_EMAIL: "myaegee-admins@${EMAIL_DOMAIN}"
      PGADMIN_DEFAULT_PASSWORD: "${PW_PGADMIN}"
      PGADMIN_LISTEN_PORT: 5050

### redis Admin Container #######################################
  redisadmin:
    image: erikdubbelboer/phpredisadmin:v1.11.4
    # environment:
      # ADMIN_USER: admin
      # ADMIN_PASS: ${PW_TRAEFIK}
      # REDIS_1_HOST: redis-oms-gsuite-wrapper
      # REDIS_1_PORT: 6379
    labels:
      - "traefik.enable=true"
      - "traefik.backend=redisadmin"
      - "traefik.port=80"
      - "traefik.frontend.rule=Host:${SUBDOMAIN_REDISADMIN}${BASE_URL}"
      - "traefik.frontend.priority=20"
      - "traefik.frontend.auth.basic.users=admin:${PW_TRAEFIK}"


### show api docs Container #######################################
  swagger:
    image: swaggerapi/swagger-ui:v3.28.0
    environment:
      # API_URL: http://events/api-docs.json
      URLS: "[{url: \"http://${SUBDOMAIN_FRONTEND}${BASE_URL}/api/core/api-docs.json\", \
              name: \"core\"}, \
              {url: \"http://${SUBDOMAIN_FRONTEND}${BASE_URL}/api/events/api-docs.json\", \
              name: \"events\"}, \
              {url: \"http://${SUBDOMAIN_FRONTEND}${BASE_URL}/api/statutory/api-docs.json\", \
              name: \"statutory\"}, \
              {url: \"http://${SUBDOMAIN_FRONTEND}${BASE_URL}/api/discounts/api-docs.json\", \
              name: \"discounts\"}, \
              {url: \"http://${SUBDOMAIN_FRONTEND}${BASE_URL}/api/network/api-docs.json\", \
              name: \"network\"}, \
              {url: \"http://${SUBDOMAIN_FRONTEND}${BASE_URL}/api/summeruniversity/api-docs.json\", \
              name: \"summeruniversity\"}, \
              {url: \"http://${SUBDOMAIN_FRONTEND}${BASE_URL}/api/knowledge/api-docs.json\", \
              name: \"knowledge\"}, \
              ]"
    labels:
      - traefik.enable=true
      - traefik.backend=swagger
      - traefik.port=8080
      - traefik.frontend.rule=Host:${SUBDOMAIN_APIDOCS}${BASE_URL}
      - traefik.frontend.priority=20

volumes:
  portainer-data:
    driver: local

networks:
  default:
    external:
      name: OMS
