{
 "title": "Traefik  Realtime Metrics",
 "description": "Visualize Traefik Metrics",
 "tags": [ "network" ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "30s",
 "panels": [
  {
   "title": "Average Response Time (ms)",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(traefik_request_duration_seconds_sum) / sum(traefik_requests_total) * 1000"
    }
   ]
  },
  {
   "title": "Uptime",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 0 },
   "format": "s",
   "valueName": "current",
   "targets": [
    {
     "expr": "time() - process_start_time_seconds{instance=\"traefik:8080\"}"
    }
   ]
  },
  {
   "title": "404 Error Count last 5 Minutes",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 0 },
   "format": "none",
   "valueName": "max",
   "targets": [
    {
     "expr": "sum(rate(traefik_requests_total{code=\"404\",method=\"GET\",service=\"http\"}[5m])) * 1000"
    }
   ]
  },
  {
   "title": "Total requests",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "none", "label": "Count" }
   ],
   "targets": [
    {
     "expr": "sum(traefik_requests_total{service=\"http\"})",
     "legendFormat": "{{http}}"
    },
    {
     "expr": "sum(traefik_requests_total{service=\"https\"})",
     "legendFormat": "{{https}}"
    }
   ]
  },
  {
   "title": "Requests by Request Code",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "traefik_requests_total{service!~\"http\"}",
     "legendFormat": "{{service}} {{method}} {{code}}"
    }
   ]
  },
  {
   "title": "Requests in last 5 minutes",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(traefik_requests_total[5m]))",
     "legendFormat": "{{requests}}"
    }
   ]
  },
  {
   "title": "Successful Status Code Count (5min)",
   "type": "graph",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 15 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(traefik_requests_total{service=~\"http|https\",code=\"200\"}[5m])",
     "legendFormat": "{{service}} {{method}} {{code}}"
    }
   ]
  },
  {
   "title": "Bad Status Code Count (5m)",
   "type": "graph",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 15 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(traefik_requests_total{service=~\"http|https\",code!=\"200\"}[5m])",
     "legendFormat": "{{service}} {{method}} {{code}}"
    }
   ]
  }
 ]
}