{
 "title": "Filesystem usage",
 "time": { "from": "now-30m", "to": "now" },
 "panels": [
  {
   "title": "% of used space on prod",
   "type": "graph",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "(1 - sum(node_filesystem_free_bytes{instance=\"traefik.barnab.eu:80\",mountpoint=\"/\"}) / sum(node_filesystem_size_bytes{instance=\"traefik.barnab.eu:80\",mountpoint=\"/\"})) * 100",
     "legendFormat": "% of used space on /"
    }
   ]
  },
  {
   "title": "% of used space on backup1",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 5 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "(1 - sum(node_filesystem_free_bytes{instance=\"traefik.b1.barnab.eu:80\",mountpoint=\"/\"}) / sum(node_filesystem_size_bytes{instance=\"traefik.b1.barnab.eu:80\",mountpoint=\"/\"})) * 100",
     "legendFormat": "% of used space on /"
    }
   ]
  },
  {
   "title": "% of used space on services",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 5 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "(1 - sum(node_filesystem_free_bytes{instance=\"traefik.svc.barnab.eu:80\",mountpoint=\"/\"}) / sum(node_filesystem_size_bytes{instance=\"traefik.svc.barnab.eu:80\",mountpoint=\"/\"})) * 100",
     "legendFormat": "% of used space on /"
    }
   ]
  },
  {
   "title": "% of used space on futureprod",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "(1 - sum(node_filesystem_free_bytes{instance=\"traefik.futureprod.barnab.eu:80\",mountpoint=\"/\"}) / sum(node_filesystem_size_bytes{instance=\"traefik.futureprod.barnab.eu:80\",mountpoint=\"/\"})) * 100",
     "legendFormat": "% of used space on /"
    }
   ]
  },
  {
   "title": "% of used space on staging (azure)",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "(1 - sum(node_filesystem_free_bytes{instance=\"traefik.stag.barnab.eu:80\",mountpoint=\"/\"}) / sum(node_filesystem_size_bytes{instance=\"traefik.stag.barnab.eu:80\",mountpoint=\"/\"})) * 100",
     "legendFormat": "% of used space on /"
    }
   ]
  },
  {
   "title": "% of used space on backup2",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 15 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "(1 - sum(node_filesystem_free_bytes{instance=\"traefik.b2.barnab.eu:80\",mountpoint=\"/\"}) / sum(node_filesystem_size_bytes{instance=\"traefik.b2.barnab.eu:80\",mountpoint=\"/\"})) * 100",
     "legendFormat": "% of used space on /"
    }
   ]
  }
 ]
}