{
 "title": "MAIN DASH",
 "time": { "from": "now-3h", "to": "now" },
 "templating": {
  "list": [
   { "name": "endpoint", "label": "Endpoint", "query": "worldping.*" },
   { "name": "probe", "label": "Probe(s)", "query": "worldping.$endpoint.*" }
  ]
 },
 "panels": [
  { "title": "Alerts", "type": "alertlist", "gridPos": { "h": 4, "w": 24, "x": 0, "y": 0 } },
  { "type": "worldping-endpoint-nav", "gridPos": { "h": 3, "w": 24, "x": 0, "y": 4 } },
  {
   "title": "DNS",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 6, "x": 0, "y": 7 },
   "format": "percent",
   "valueName": "avg",
   "targets": [
    {
     "target": "scale(averageSeries(worldping.$endpoint.$probe.dns.ok_state), 100)"
    }
   ]
  },
  {
   "title": "HTTPS",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 6, "x": 6, "y": 7 },
   "format": "percent",
   "valueName": "avg",
   "targets": [
    {
     "target": "scale(averageSeries(worldping.$endpoint.$probe.https.ok_state), 100)"
    }
   ]
  },
  { "title": "Dashboards", "type": "dashlist", "gridPos": { "h": 21, "w": 12, "x": 12, "y": 7 } },
  {
   "title": "DNS",
   "type": "graph",
   "gridPos": { "h": 3, "w": 6, "x": 0, "y": 10 },
   "targets": [
    {
     "target": "alias(consolidateBy(sumSeries(worldping.$endpoint.$probe.dns.error_state), 'sum'), 'error')"
    },
    {
     "target": "alias(consolidateBy(sumSeries(worldping.$endpoint.$probe.dns.ok_state), 'sum'), 'ok')"
    }
   ]
  },
  {
   "title": "HTTPS",
   "type": "graph",
   "gridPos": { "h": 3, "w": 6, "x": 6, "y": 10 },
   "targets": [
    {
     "target": "alias(consolidateBy(sumSeries(worldping.$endpoint.$probe.https.error_state), 'sum'), 'error')"
    },
    {
     "target": "alias(consolidateBy(sumSeries(worldping.$endpoint.$probe.https.ok_state), 'sum'), 'ok')"
    }
   ]
  },
  {
   "title": "DNS response by Probe",
   "type": "graph",
   "gridPos": { "h": 15, "w": 6, "x": 0, "y": 13 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "target": "aliasByNode(sortByName(worldping.$endpoint.$probe.dns.time), 2)"
    }
   ]
  },
  {
   "title": "HTTPS response by Probe",
   "type": "graph",
   "gridPos": { "h": 15, "w": 6, "x": 6, "y": 13 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "target": "aliasByNode(sortByName(worldping.$endpoint.$probe.https.total), 2)"
    }
   ]
  }
 ]
}