version: "3.4"

### GSUITE WRAPPER   #######################################
services:
  redis-gsuite-wrapper:
    restart: always
    image: redis:6.2.6-alpine
    volumes:
      - redis_gsuite_persistence:/data

  gsuite-wrapper:
    restart: on-failure
    image: aegee/gsuite-wrapper:latest
    links:
      - redis-gsuite-wrapper
    expose:
      - 8084
    volumes:
      - ./${PATH_GSUITE_WRAPPER}/../lib/config/myaegee-serviceaccount.json:/usr/app/src/lib/config/myaegee-serviceaccount.json
      - ./${PATH_GSUITE_WRAPPER}/../lib/config/secrets.json:/usr/app/src/lib/config/secrets.json
    environment:
      NODE_ENV: "${MYAEGEE_ENV}"
      # BUGSNAG_KEY: "${BUGSNAG_KEY_GSUITE_WRAPPER}"
    labels:
      - "traefik.backend=gsuite-wrapper"
      - "traefik.port=8084"
      - "traefik.hc.frontend.rule=Path:/api/gsuite-wrapper/healthcheck;PathPrefixStrip:/api/gsuite-wrapper"
      - "traefik.doc.frontend.rule=Path:/api/gsuite-wrapper/api-docs.json;PathPrefixStrip:/api/gsuite-wrapper"
      - "traefik.enable=true"

volumes:
  redis_gsuite_persistence:
    driver: "local"

networks:
  default:
    external:
      name: OMS
