module.exports = {
    EVENT_MINIMAL_FIELDS: [
        'id',
        'name',
        'url',
        'image',
        'description',
        'email',
        'starts',
        'ends',
        'fee',
        'organizing_bodies',
        'locations',
        'type',
        'theme_category',
        'theme',
        'max_participants',
        'accommodation_type',
        'optional_fee',
        'optional_programme'
    ],
    EVENT_FULL_FIELDS: [
        'id',
        'name',
        'url',
        'image',
        'photos',
        'video',
        'description',
        'email',
        'website',
        'social_media',
        'starts',
        'ends',
        'fee',
        'organizing_bodies',
        'locations',
        'type',
        'theme_category',
        'theme',
        'trainers',
        'pax_description',
        'pax_confirmation',
        'max_participants',
        'activities_list',
        'course_level',
        'courses',
        'special_equipment',
        'university_support',
        'optional_fee',
        'optional_programme'
    ],
    EVENT_TYPES: ['regular', 'pilot'],
    CURRENT_USER_PREFIX: 'me'
};
