version: "3.4"
### OMS DISCOUNTS     #######################################
services:
    postgres-discounts:
        image: postgres:10.18
        volumes:
            - postgres-discounts:/var/lib/postgresql/data
        expose:
            - "5432"
        environment:
            POSTGRES_USER: "postgres"
            POSTGRES_PASSWORD: "${PW_POSTGRES}"

    discounts:
        image: aegee/discounts:latest
        volumes:
            - discounts-media:/usr/app/media
            - shared:/usr/app/shared:ro
        depends_on:
            - postgres-discounts
        expose:
            - "8084"
        environment:
            BUGSNAG_KEY: "${BUGSNAG_KEY_DISCOUNTS}"
            PG_PASSWORD: "${PW_POSTGRES}"
            NODE_ENV: "${MYAEGEE_ENV}"
            HOST: "${SUBDOMAIN_FRONTEND}${BASE_URL}"
        healthcheck:
            test: ["CMD", "curl", "-f", "http://localhost:8084/healthcheck"]
            interval: 30s
            timeout: 10s
            retries: 3
            start_period: 40s
        # cpu_count: 1
        # mem_limit: 900m
        labels:
            - "traefik.backend=discounts"
            - "traefik.port=8084"
            - "traefik.auth.frontend.rule=PathPrefix:/api/discounts/metrics;PathPrefixStrip:/api/discounts;"
            - "traefik.old.frontend.rule=PathPrefixStrip:/services/oms-discounts/api;"
            - "traefik.new.frontend.rule=PathPrefixStrip:/api/discounts;"
            - "traefik.auth.frontend.auth.basic.users=admin:${METRICS_CREDENTIALS}"
            - "traefik.old.frontend.priority=110"
            - "traefik.new.frontend.priority=110"
            - "traefik.auth.frontend.priority=120"
            - "traefik.enable=true"

volumes:
    postgres-discounts:
        driver: local
    discounts-media:
        driver: local
    shared:
        driver: local

networks:
    default:
        external:
            name: OMS
