version: "3.4"
### OMS DISCOUNTS     #######################################
services:
    postgres-discounts:
        image: postgres:10.18
        volumes:
            - postgres-discounts:/var/lib/postgresql/data
        expose:
            - "5432"
        environment:
            POSTGRES_USER: "postgres"
            POSTGRES_PASSWORD: "${PW_POSTGRES}"
        labels:
            # we don't access via traefik
            - "traefik.enable=false"

    discounts:
        image: aegee/discounts:latest
        volumes:
            - discounts-media:/usr/app/media
            - shared:/usr/app/shared:ro
        depends_on:
            - postgres-discounts
        expose:
            - "8084"
        environment:
            BUGSNAG_KEY: "${BUGSNAG_KEY_DISCOUNTS}"
            PG_PASSWORD: "${PW_POSTGRES}"
            NODE_ENV: "${MYAEGEE_ENV}"
            HOST: "${SUBDOMAIN_FRONTEND}${BASE_URL}"
        healthcheck:
            test: ["CMD", "curl", "-f", "http://localhost:8084/healthcheck"]
            interval: 30s
            timeout: 10s
            retries: 3
            start_period: 40s
        # cpu_count: 1
        # mem_limit: 900m
        labels:
            - "traefik.http.routers.discounts.rule=Host(`${SUBDOMAIN_FRONTEND}${BASE_URL}`) && PathPrefix(`/api/discounts`)"
            - "traefik.http.routers.discounts.tls=true"

            - "traefik.http.routers.discounts.middlewares=discounts-stripprefix"
            - "traefik.http.middlewares.discounts-stripprefix.stripprefix.prefixes=/api/discounts"

            - "traefik.http.routers.metrics.rule=Host(`${SUBDOMAIN_FRONTEND}${BASE_URL}`) && PathPrefix(`/api/discounts/metrics`)"
            - "traefik.http.routers.metrics.middlewares=discounts-stripprefix, metricsauthdiscounts"

            - "traefik.http.middlewares.metricsauthdiscounts.basicauth.users=admin:${METRICS_CREDENTIALS}"

volumes:
    postgres-discounts:
        driver: local
    discounts-media:
        driver: local
    shared:
        driver: local

networks:
    default:
        external:
            name: OMS
