version: "3.4"
services:
    postgres-summeruniversity:
        restart: always
        image: postgres:10.18
        volumes:
            - postgres-summeruniversity:/var/lib/postgresql/data
        expose:
            - "5432"
        environment:
            POSTGRES_USER: "postgres"
            POSTGRES_PASSWORD: "${PW_POSTGRES}"
        labels:
            # we don't access via traefik
            - "traefik.enable=false"

    summeruniversity:
        restart: on-failure
        image: aegee/summeruniversity:latest
        volumes:
            - summeruniversity-media:/usr/app/media
            - shared:/usr/app/shared:ro
        depends_on:
            - postgres-summeruniversity
        expose:
            - "8084"
        environment:
            BUGSNAG_KEY: "${BUGSNAG_KEY_SUMMERUNIVERSITY}"
            PG_PASSWORD: "${PW_POSTGRES}"
            NODE_ENV: "${MYAEGEE_ENV}"
            HOST: "${SUBDOMAIN_FRONTEND}${BASE_URL}"
            CORE_LOGIN: "${CORE_LOGIN}"
            CORE_PASSWORD: "${CORE_PASSWORD}"
        healthcheck:
            test: ["CMD", "curl", "-f", "http://localhost:8084/healthcheck"]
            interval: 30s
            timeout: 10s
            retries: 3
            start_period: 40s
        # cpu_count: 1
        # mem_limit: 900m
        labels:
            - "traefik.enable=true"
            - "traefik.http.routers.summeruniversity.entrypoints=websecure"
            - "traefik.http.routers.summeruniversity.tls=true"
            - "traefik.http.routers.summeruniversity.rule=Host(`${SUBDOMAIN_FRONTEND}${BASE_URL}`) && PathPrefix(`/api/summeruniversity`)"

            - "traefik.http.routers.summeruniversity.middlewares=summeruniversity-stripprefix"
            - "traefik.http.middlewares.summeruniversity-stripprefix.stripprefix.prefixes=/api/summeruniversity"

            - "traefik.http.routers.metrics.rule=Host(`${SUBDOMAIN_FRONTEND}${BASE_URL}`) && PathPrefix(`/api/summeruniversity/metrics`)"
            - "traefik.http.routers.metrics.middlewares=summeruniversity-stripprefix, metricsauth"

    summeruniversity-static:
        restart: on-failure
        image: aegee/nginx-static:prod
        volumes:
            - summeruniversity-media:/usr/app/media:ro
            - shared:/usr/app/shared:ro
        expose:
            - "80"
        healthcheck:
            test: ["CMD", "curl", "-f", "http://localhost:80/healthcheck"]
            interval: 30s
            timeout: 10s
            retries: 3
            start_period: 40s
        labels:
            - "traefik.enable=true"
            - "traefik.http.routers.summeruniversity-static.rule=PathPrefix(`/media/summeruniversity`)"
            - "traefik.http.routers.summeruniversity-static.middlewares=summeruniversity-static-stripprefix"
            - "traefik.http.middlewares.summeruniversity-static-stripprefix.stripprefix.prefixes=/media/summeruniversity"

volumes:
    postgres-summeruniversity:
        driver: local
    summeruniversity-media:
        driver: local
    shared:
        driver: local

networks:
    default:
        external:
            name: OMS
