version: '2'

services:

### OMS TUNNEL        #######################################
### Proxy container #######################################

    traefik:
        image: aegee/traefik:dev
        ports:
            - "80:80"
            - "8080:8080"
            - "443:443"
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock

### service registry #######################################
#https://github.com/AEGEE/oms-docker/blob/45dff00d8db4dbac1242cf43e7420c42ee723250/docker-dev/docker-compose.yml

### OMS CORE        #######################################
### Applications Code Container #############################

    omscore-data:
        image: tianon/true
        volumes:
            - "../oms-core:/var/www"
            - shared:/var/shared

### PHP-FPM Container #######################################

    php-fpm:
        image: aegee/php-fpm:dev
        volumes_from:
            - omscore-data
        expose:
            - "9000"

### Nginx Server Container ##################################

    omscore-nginx:
        image: aegee/omscore-nginx:dev
        volumes_from:
            - omscore-data
        links:
            - php-fpm
        expose:
            - "80"
        labels:
            - "traefik.backend=omscore"
            - "traefik.port=80"
            - "traefik.frontend.rule=HostRegexp:{domain:[a-z0-9.]+}"
            - "traefik.frontend.priority=10"
            - "traefik.enable=true"
            - "registry.categories=(users, 10);(antennae, 10);(notifications, 0)"
            - "registry.backend=/api"
            - "registry.description=The core module with both backend and frontend"

### PostgreSQL Container ####################################

    postgres:
        image: postgres:latest
        volumes:
            - postgres:/var/lib/postgresql/data
        expose:
            - "5432"
        environment:
            POSTGRES_DB: homestead
            POSTGRES_USER: homestead
            POSTGRES_PASSWORD: secret

### pgAdmin Container #######################################

    pgadmin:
        image: fenglc/pgadmin4
        ports:
            - "8081:5050"
        links:
            - postgres

### OMS EVENTS        #######################################
### mongodb Container #######################################
#https://github.com/AEGEE/oms-docker/blob/45dff00d8db4dbac1242cf43e7420c42ee723250/docker-dev/docker-compose.yml


### OMS APPLICATIONS           #######################################
### Applications to oms-events #######################################
#https://github.com/AEGEE/oms-docker/blob/45dff00d8db4dbac1242cf43e7420c42ee723250/docker-dev/docker-compose.yml

### Volumes Setup ###########################################

volumes:
    postgres:
        driver: "local"
    mongodb:
        driver: "local"
    omsevents_media:
        driver: "local"
    shared:
        driver: "local"
