version: "3.4"
### OMS STATUTORY     #######################################
services:
  oms-core-js:
    build:
      context: ./${PATH_OMS_CORE_JS}/..
      dockerfile: ./docker/oms-statutory/Dockerfile
    image: aegee/oms-statutory:dev
    volumes:
      - /usr/app/src/node_modules
      - ./${PATH_OMS_CORE_JS}/../:/usr/app/src
