FROM node:8

RUN npm install -g supervisor bunyan && \
	mkdir -p /usr/scripts && mkdir -p /usr/shared && \
	npm cache clean --force

WORKDIR /usr/app
ENV PORT=8085

RUN git clone https://github.com/AEGEE/oms-applications.git /usr/app && \
	npm install

CMD supervisor -e 'node,js,json' /usr/app/lib/server.js | bunyan

EXPOSE 8085
