FROM node:8

RUN npm install -g supervisor bunyan && \
	mkdir -p /usr/scripts && mkdir -p /usr/shared && \
	npm cache clean --force

WORKDIR /usr/app
ENV PORT=8085

CMD npm install && supervisor -e 'node,js,json' /usr/app/lib/server.js | bunyan

EXPOSE 8085
