module.exports = {
    CURRENT_USER_PREFIX: 'me',
    ALLOWED_NETWORK_LIST_FIELDS: [
        'id',
        'user_id',
        'body_id',
        'body_name',
        'participant_type',
        'participant_order',
        'first_name',
        'last_name',
        'is_on_memberslist'
    ],
    ALLOWED_JURIDICAL_LIST_FIELDS: [
        'id',
        'user_id',
        'body_id',
        'body_name',
        'participant_type',
        'participant_order',
        'cancelled',
        'paid_fee',
        'attended',
        'registered',
        'departed',
        'first_name',
        'last_name',
        'status',
        'created_at',
        'updated_at'
    ],
    ALLOWED_INCOMING_FIELDS: [
        'id',
        'user_id',
        'body_id',
        'body_name',
        'participant_type',
        'participant_order',
        'paid_fee',
        'attended',
        'registered',
        'departed',
        'first_name',
        'last_name',
        'meals',
        'allergies',
        'email',
        'gender',
        'nationality',
        'visa_place_of_birth',
        'visa_passport_number',
        'visa_passport_issue_date',
        'visa_passport_expiration_date',
        'visa_passport_issue_authority',
        'visa_embassy',
        'visa_street_and_house',
        'visa_postal_code',
        'visa_city',
        'visa_country',
        'date_of_birth',
        'created_at',
        'updated_at'
    ],
    ALLOWED_PARTICIPANTS_LIST_FIELDS: [
        'id',
        'user_id',
        'body_id',
        'body_name',
        'participant_type',
        'participant_order',
        'cancelled',
        'paid_fee',
        'attended',
        'registered',
        'departed',
        'first_name',
        'last_name',
        'created_at',
        'updated_at'
    ],
    ALLOWED_PLENARY_ATTENDANCE_FIELDS: [
        'id',
        'first_name',
        'last_name',
        'participant_type',
        'participant_order',
        'body_id',
        'body_name'
    ],
    APPLICATION_FIELD_NAMES: {
        id: 'ID',
        user_id: 'User ID',
        body_id: 'Body ID',
        created_at: 'Applied on',
        updated_at: 'Updated at',
        is_on_memberslist: 'Is on memberslist?',
        visa_required: 'Visa required?',
        participant_type: 'Participant type',
        participant_order: 'Participant order',
        board_comment: 'Board comment',
        status: 'Status',
        cancelled: 'Cancelled?',
        paid_fee: 'Confirmed?',
        attended: 'Attended?',
        registered: 'JC registered?',
        departed: 'Departed?',
        first_name: 'First name',
        last_name: 'Last name',
        email: 'Email',
        gender: 'Gender',
        body_name: 'Body name',
        nationality: 'Nationality',
        visa_place_of_birth: 'Visa: place of birth',
        visa_passport_number: 'Visa: passport number',
        visa_passport_issue_date: 'Visa: passport issue date',
        visa_passport_expiration_date: 'Visa: passport expiration date',
        visa_passport_issue_authority: 'Visa: passport issue authority',
        visa_embassy: 'Visa: embassy',
        visa_street_and_house: 'Visa: street and house number',
        visa_postal_code: 'Visa: postal code',
        visa_city: 'Visa: city',
        visa_country: 'Visa: country',
        date_of_birth: 'Date of birth',
        number_of_events_visited: 'Number of Agora/EPM visited',
        meals: 'Meals',
        allergies: 'Allergies'
    }
};
