version: "3.4"
### CORE     #######################################
services:
  core:
    build:
      context: ./${PATH_CORE}/..
      dockerfile: ./docker/core/Dockerfile
    image: aegee/core:dev
    command: sh -c "sh /usr/app/scripts/bootstrap.sh && nodemon -L -e 'js,json' lib/run.js | bunyan --color"
    volumes:
      - ./${PATH_CORE}/../config/:/usr/app/src/config
      - ./${PATH_CORE}/../lib/:/usr/app/src/lib
      - ./${PATH_CORE}/../middlewares/:/usr/app/src/middlewares
      - ./${PATH_CORE}/../migrations/:/usr/app/src/migrations
      - ./${PATH_CORE}/../models/:/usr/app/src/models
      - ./${PATH_CORE}/../scripts/:/usr/app/src/scripts
      - ./${PATH_CORE}/../cli.js/:/usr/app/src/cli.js
