{
 "title": "statutory main dashboard",
 "time": { "from": "now-30m", "to": "now" },
 "panels": [
  {
   "title": "pax by event and type",
   "type": "graph",
   "gridPos": { "h": 12, "w": 19, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(statutory_applications_total) by (event_name)",
     "legendFormat": "{{ event_name }}"
    }
   ]
  },
  {
   "title": "applications total",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 5, "x": 19, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(statutory_applications_total)"
    }
   ]
  },
  {
   "title": "events total",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 5, "x": 19, "y": 4 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    { "expr": "sum(statutory_events_total)" }
   ]
  },
  {
   "title": "memberslists total",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 5, "x": 19, "y": 8 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(statutory_memberslists_total)"
    }
   ]
  },
  {
   "title": "candidates by event and position",
   "type": "graph",
   "gridPos": { "h": 11, "w": 19, "x": 0, "y": 12 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(statutory_candidates_total) by (event_name, position_name)",
     "legendFormat": "{{ position_name }} @ {{ event_name }}"
    }
   ]
  }
 ]
}