version: '2'

services:

### OMS TUNNEL        #######################################
### Proxy container #######################################

    traefik:
        image: aegee/traefik:dev
        ports:
            - "80:80"
            - "8080:8080"
            - "443:443"
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock

### service registry #######################################
#https://github.com/AEGEE/oms-docker/blob/45dff00d8db4dbac1242cf43e7420c42ee723250/docker-dev/docker-compose.yml


### OMS EVENTS        #######################################
### mongodb Container #######################################
#https://github.com/AEGEE/oms-docker/blob/45dff00d8db4dbac1242cf43e7420c42ee723250/docker-dev/docker-compose.yml


### OMS APPLICATIONS           #######################################
### Applications to oms-events #######################################
#https://github.com/AEGEE/oms-docker/blob/45dff00d8db4dbac1242cf43e7420c42ee723250/docker-dev/docker-compose.yml

### Volumes Setup ###########################################

volumes:
    postgres:
        driver: "local"
    mongodb:
        driver: "local"
    omsevents_media:
        driver: "local"
    shared:
        driver: "local"
