FROM node:8

RUN npm install -g supervisor bunyan && \
	npm cache clean --force

RUN mkdir -p /usr/src/shared

###UNTIL HERE SAME AS SERVICEREGISTRY
#WORKDIR /usr/src/app

RUN mkdir -p /usr/app/ \
        && mkdir -p /usr/app/frontend \
        && mkdir -p /usr/app/media \
        && mkdir -p /usr/scripts \
        && mkdir -p /usr/shared

WORKDIR /usr/app

ADD ./configFile.json /usr/scripts/configFile.json

CMD cp /usr/scripts/configFile.json /usr/app/lib/config/configFile.json && \
	npm install && \
	supervisor -e 'node,js,json' /usr/app/lib/server.js | bunyan

EXPOSE 8082
