version: "3.4"
### KNOWLEDGE     #######################################
services:
    postgres-knowledge:
        image: postgres:10.18
        volumes:
            - postgres-knowledge:/var/lib/postgresql/data
        expose:
            - "5432"
        environment:
            POSTGRES_USER: "postgres"
            POSTGRES_PASSWORD: "${PW_POSTGRES}"
        labels:
            # we don't access via traefik
            - "traefik.enable=false"

    knowledge:
        image: aegee/knowledge:latest
        volumes:
            - knowledge-media:/usr/app/media
            - shared:/usr/app/shared:ro
        depends_on:
            - postgres-knowledge
        expose:
            - "8084"
        environment:
            BUGSNAG_KEY: "${BUGSNAG_KEY_KNOWLEDGE}"
            PG_PASSWORD: "${PW_POSTGRES}"
            NODE_ENV: "${MYAEGEE_ENV}"
            HOST: "${SUBDOMAIN_FRONTEND}${BASE_URL}"
        healthcheck:
            test: ["CMD", "curl", "-f", "http://localhost:8084/healthcheck"]
            interval: 30s
            timeout: 10s
            retries: 3
            start_period: 40s
        # cpu_count: 1
        # mem_limit: 900m
        labels:
            - "traefik.enable=true"
            - "traefik.http.routers.knowledge.entrypoints=websecure"
            - "traefik.http.routers.knowledge.tls=true"
            - "traefik.http.routers.knowledge.rule=Host(`${SUBDOMAIN_FRONTEND}${BASE_URL}`) && PathPrefix(`/api/knowledge`)"

            - "traefik.http.routers.knowledge.middlewares=knowledge-stripprefix"
            - "traefik.http.middlewares.knowledge-stripprefix.stripprefix.prefixes=/api/knowledge"

            - "traefik.http.routers.metrics.rule=Host(`${SUBDOMAIN_FRONTEND}${BASE_URL}`) && PathPrefix(`/api/knowledge/metrics`)"
            - "traefik.http.routers.metrics.middlewares=knowledge-stripprefix, metricsauth"

volumes:
    postgres-knowledge:
        driver: local
    knowledge-media:
        driver: local
    shared:
        driver: local

networks:
    default:
        external:
            name: OMS
