# my global config
global:
  scrape_interval:     60s # Set the scrape interval to every 15 seconds. Default is every 1 minute.
  evaluation_interval: 60s # Evaluate rules every 15 seconds. The default is every 1 minute.
  # scrape_timeout is set to the global default (10s).

  # Attach these labels to any time series or alerts when communicating with
  # external systems (federation, remote storage, Alertmanager).
  external_labels:
      monitor: 'oms-monitor'

# Load rules once and periodically evaluate them according to the global 'evaluation_interval'.
rule_files:
  # - "first.rules"
  # - "second.rules"

# A scrape configuration containing exactly one endpoint to scrape:
# Here it's Prometheus itself.
scrape_configs:
  # The job name is added as a label `job=<job_name>` to any timeseries scraped from this config.
  - job_name: 'base-metrics'
    # metrics_path defaults to '/metrics'
    # scheme defaults to 'http'.
    static_configs:
      - targets: ['traefik:8080', 'cadvisor:8080', 'node-exporter:9100']
  - job_name: 'api-endpoints' #PRODUCTION CONFIG
    # metrics_path defaults to '/metrics'
    # scheme defaults to 'http'.
    static_configs:
        - targets: ['oms-core-elixir:4000', 'oms-events:8084', 'oms-statutory:8084']

  # Scraping also production stuff (ONLY FROM STAGING --REMOVE ON PROD)
  - job_name: 'statutory-metrics'
    static_configs:
      - targets: ['my.aegee.eu']
    metrics_path: '/services/oms-statutory/api/metrics'
  - job_name: 'statutory-metrics-endpoints'
    static_configs:
      - targets: ['my.aegee.eu']
    scrape_interval: 10s
    metrics_path: '/services/oms-statutory/api/metrics/requests'
  - job_name: 'events-metrics'
    static_configs:
      - targets: ['my.aegee.eu']
    metrics_path: '/services/oms-events/api/metrics'
  - job_name: 'events-metrics-endpoints'
    static_configs:
      - targets: ['my.aegee.eu']
    scrape_interval: 10s
    metrics_path: '/services/oms-events/api/metrics/requests'
  - job_name: 'discounts-metrics'
    static_configs:
      - targets: ['my.aegee.eu']
    metrics_path: '/services/oms-discounts/api/metrics'
  - job_name: 'discounts-metrics-endpoints'
    static_configs:
      - targets: ['my.aegee.eu']
    scrape_interval: 10s
    metrics_path: '/services/oms-discounts/api/metrics/requests'
