# my global config
global:
  scrape_interval: 60s  # Set the scrape interval to every 15 seconds. Default is every 1 minute.
  evaluation_interval: 60s  # Evaluate rules every 15 seconds. The default is every 1 minute.
  # scrape_timeout is set to the global default (10s).

  # Attach these labels to any time series or alerts when communicating with
  # external systems (federation, remote storage, Alertmanager).
  external_labels:
    monitor: 'monitor-from-${HOSTNAME}'

# Load rules once and periodically evaluate them according to the global 'evaluation_interval'.
rule_files:
  # - "first.rules"
  # - "second.rules"

# A scrape configuration containing exactly one endpoint to scrape:
# Here it's Prometheus itself.
scrape_configs:
  # The job name is added as a label `job=<job_name>` to any timeseries scraped from this config.
  - job_name: 'scrape-app-diagnostics'
    # metrics_path defaults to '/metrics'
    # scheme defaults to 'http'.
    static_configs:
      - targets:
          - 'statping:8080'
          - 'upmonitor:3000'
          - 'prometheus:9090'
          - 'grafana:3000'
    bearer_token: ${STATPING_TOKEN} # I presume this header is ignored by other services

  - job_name: 'node-diagnostics'
    basic_auth:
      username: ${TRAEFIK_USERNAME}
      password: ${TRAEFIK_PASSWORD}
    static_configs:
      - targets:
          - 'traefik.aegee.eu'
          - 'traefik.staging.aegee.eu'
          - 'traefik.services.aegee.eu'
        labels:
          group: 'applications'
      - targets:
          - 'traefik.commander.aegee.eu'
          - 'traefik.monitor1.aegee.eu'
          - 'traefik.monitor2.aegee.eu'
        labels:
          group: 'diagnostics'
    metrics_path: '/ext-metrics/node-exporter/metrics'

  - job_name: 'container-diagnostics'
    basic_auth:
      username: ${TRAEFIK_USERNAME}
      password: ${TRAEFIK_PASSWORD}
    static_configs:
      - targets:
          - 'traefik.aegee.eu'
          - 'traefik.staging.aegee.eu'
          - 'traefik.services.aegee.eu'
        labels:
          group: 'applications'
      - targets:
          - 'traefik.commander.aegee.eu'
          - 'traefik.monitor1.aegee.eu'
          - 'traefik.monitor2.aegee.eu'
        labels:
          group: 'diagnostics'
    metrics_path: '/ext-metrics/cadvisor/metrics'

  - job_name: 'traefik-diagnostics'
  # READ: https://docs.traefik.io/v1.7/configuration/api/#security
    basic_auth:
      username: ${TRAEFIK_USERNAME}
      password: ${TRAEFIK_PASSWORD}
    static_configs:
      - targets:
          - 'traefik.aegee.eu'
          - 'traefik.staging.aegee.eu'
          - 'traefik.services.aegee.eu'
        labels:
          group: 'applications'
      - targets:
          - 'traefik.commander.aegee.eu'
          - 'traefik.monitor1.aegee.eu'
          - 'traefik.monitor2.aegee.eu'
        labels:
          group: 'diagnostics'
    metrics_path: '/metrics'


  # - job_name: 'blackbox'
  #   metrics_path: /probe
  #   params:
  #     module: [http_2xx]  # Look for a HTTP 200 response.
  #   static_configs:
  #     - targets:
  #       - http://my.staging.aegee.eu    # Target to probe with http.
  #       - https://my.aegee.eu   # Target to probe with https.
  #       - http://example.com:8080 # Target to probe with http on port 8080.
  #   relabel_configs:
  #     - source_labels: [__address__]
  #       target_label: __param_target
  #     - source_labels: [__param_target]
  #       target_label: instance
  #     - target_label: __address__
  #       replacement: blackbox-exporter:9115  # The blackbox exporter's real hostname:port.


  # Scraping also production stuff (ONLY FROM MONITORING HOST)
  - job_name: 'statutory-statistics'
    static_configs:
      - targets: ['my.aegee.eu']
    metrics_path: '/services/oms-statutory/api/metrics'
  - job_name: 'statutory-metrics'
    static_configs:
      - targets: ['my.aegee.eu']
    scrape_interval: 10s
    metrics_path: '/services/oms-statutory/api/metrics/requests'

  - job_name: 'events-statistics'
    static_configs:
      - targets: ['my.aegee.eu']
    metrics_path: '/services/oms-events/api/metrics'
  - job_name: 'events-metrics'
    static_configs:
      - targets: ['my.aegee.eu']
    scrape_interval: 10s
    metrics_path: '/services/oms-events/api/metrics/requests'

  - job_name: 'discounts-statistics'
    static_configs:
      - targets: ['my.aegee.eu']
    metrics_path: '/services/oms-discounts/api/metrics'
  - job_name: 'discounts-metrics'
    static_configs:
      - targets: ['my.aegee.eu']
    scrape_interval: 10s
    metrics_path: '/services/oms-discounts/api/metrics/requests'
