version: "3.4"

services:

  rabbit:
    image: aegee/rabbit
    restart: always
    expose:
      - 5672
      - 15672
    labels:
      - "traefik.frontend.rule=Host:${SUBDOMAIN_RABBITMQ}${BASE_URL};PathPrefix:/"
      - "traefik.backend=rabbit"
      - "traefik.port=15672"
      - "traefik.enable=true"

  # Not a webservice, but a worker service
  dispatcher:
    image: aegee/dispatcher
    restart: always


networks:
  default:
    external:
      name: OMS
