FROM python:3.12-slim

WORKDIR /usr/app

RUN pip install --no-cache-dir pika==1.3.2 Faker==37.0.0

COPY ./helpers /usr/app/helpers
COPY ./templates /usr/app/templates

WORKDIR /usr/app/helpers

ENV RABBIT_HOST=rabbit

ENTRYPOINT ["python", "-u", "send.py"]
