version: "3.4"

services:

  rabbit: # login with guest:guest
    image: aegee/rabbit:3.11-mgmt-delayxch
    restart: always
    expose:
      - 5672
      - 15672
    # environment:
    #   RABBITMQ_DEFAULT_USER: "admin"
    #   RABBITMQ_DEFAULT_PASS: "5ecr3t"
    labels:
      - "traefik.frontend.rule=Host:${SUBDOMAIN_RABBITMQ}${BASE_URL};PathPrefix:/"
      - "traefik.backend=rabbit"
      - "traefik.port=15672"
      - "traefik.enable=true"

  # Not a webservice, but a worker service
  dispatcher:
    image: aegee/dispatcher
    restart: always
    environment:
      ENV: "${MYAEGEE_ENV}"
      EMAIL_HOST: "${ETHEREAL_SMTP_HOST}"
      EMAIL_PORT: "${ETHEREAL_PORT}"
      EMAIL_ADDRESS: "${ETHEREAL_USER}"
      EMAIL_PASSWORD: "${ETHEREAL_PW}"
      NOTIFY_CHANNEL: "slack-tests-programmatic-stuff-other"
    volumes:
      - ./secrets/tokens.json:/usr/app/tokens.json


networks:
  default:
    external:
      name: OMS
