version: "3.4"
services:

  grafana:
    restart: on-failure
    image: grafana/grafana:6.7.1
    volumes:
      - grafana-storage:/var/lib/grafana
      - ./${PATH_MONITOR}/config/gf-provisioning:/etc/grafana/provisioning
      - ./${PATH_MONITOR}/gf-dashboards/metrics:/var/lib/grafana/dashboards/metrics
      - ./${PATH_MONITOR}/gf-dashboards/statistics:/var/lib/grafana/dashboards/statistics
    environment:
      GF_SECURITY_ADMIN_PASSWORD: "${PW_GRAFANA}"
      GF_SERVER_ROOT_URL: "https://${SUBDOMAIN_GRAFANA}${BASE_URL}/"
      # yamllint disable-line rule:line-length
      GF_INSTALL_PLUGINS: "grafana-googlesheets-datasource,raintank-worldping-app,grafana-simple-json-datasource,grafana-clock-panel,grafana-piechart-panel"
      GF_SMTP_ENABLED: "true"
      GF_SMTP_HOST: "${SENDGRID_SMTP_HOST}:587"
      GF_SMTP_USER: "${SENDGRID_USER}"
      GF_SMTP_PASSWORD: "${SENDGRID_PW}"
      GF_SMTP_FROM_ADDRESS: "grafana@${BASE_URL}"
      GF_SMTP_FROM_NAME: "AEGEE Dashboards"
    labels:
      - "traefik.backend=grafana"
      - "traefik.port=3000"
      - "traefik.frontend.rule=Host:${SUBDOMAIN_GRAFANA}${BASE_URL};PathPrefix:/"
      - "traefik.frontend.priority=110"
      - "traefik.enable=true"

  prometheus:
    restart: on-failure
    image: prom/prometheus:v2.10.0
    volumes:
      - prometheus-storage:/prometheus
      - ./${PATH_MONITOR}/config/prometheus.yml:/etc/prometheus/prometheus.yml:ro
    labels:
      - "traefik.backend=prometheus"
      - "traefik.port=9090"
      - "traefik.frontend.rule=Host:${SUBDOMAIN_PROMETHEUS}${BASE_URL};PathPrefix:/"
      - "traefik.frontend.priority=110"
      - "traefik.enable=true"
      - "traefik.frontend.auth.basic.users=admin:${PW_TRAEFIK}"

  # alternative to ciao, but more similar to cachet
  statping:
    image: hunterlong/statping:v0.80.65
    environment:
      DB_CONN: sqlite
      NAME: "MyAEGEE Statping"
      DESCRIPTION: "Statping to check on AEGEE IT services"
      DOMAIN: "https://${SUBDOMAIN_STATPING}${BASE_URL}"
      ADMIN_USER: admin
      ADMIN_PASSWORD: ${PW_STATPING}
      ADMIN_EMAIL: "myaegee-admins@${EMAIL_DOMAIN}"
      USE_CDN: "true"
      DISABLE_LOGS: "false"  # disable logs from appearing and writing to disk
      IS_DOCKER: "true"
      IS_AWS: "false"
      CMD_FILE: /bin/ash
      SASS: /usr/local/bin/sass
    volumes:
      - statping-storage:/app
    labels:
      - "traefik.backend=statping"
      - "traefik.port=8080"
      - "traefik.frontend.rule=Host:${SUBDOMAIN_STATPING}${BASE_URL};PathPrefix:/"
      - "traefik.frontend.priority=110"
      - "traefik.enable=true"

  # #alternative to worldping
  # blackbox-exporter:
  #   image: prom/blackbox-exporter:v0.16.0
  #   volumes:
  #     - ./${PATH_MONITOR}/config/blackbox.yml:/config/blackbox.yml
  #   command: '--config.file=/config/blackbox.yml'
  #   labels:
  #     - "traefik.backend=blackbox-exporter"
  #     - "traefik.port=9115"
  # yamllint disable-line rule:line-length
  #     - "traefik.frontend.rule=Host:${BASE_URL};PathPrefix:/services/blackbox-exporter;PathPrefixStrip:/services/blackbox-exporter"
  #     - "traefik.frontend.priority=110"
  #     - "traefik.enable=true"

  logstash:
    build:
      context: ./${PATH_MONITOR}/logstash/
      args:
        ELK_VERSION: ${ELK_VERSION:-7.6.0}
    volumes:
      - ./${PATH_MONITOR}/logstash/config/logstash.yml:/usr/share/logstash/config/logstash.yml:ro
      - ./${PATH_MONITOR}/logstash/pipeline:/usr/share/logstash/pipeline:ro
    ports:
      - "5000:5000"
      - "9600:9600"
    environment:
      LS_JAVA_OPTS: "-Xmx256m -Xms256m"
      ELASTIC_HOST: "${ELASTIC_HOST}"
      ELASTIC_USER: "${ELASTIC_USER}"
      ELASTIC_PASSWORD: "${ELASTIC_PASSWORD}"

volumes:
  prometheus-storage:  # TODO: set backup
    driver: local
  grafana-storage:
    driver: local
  statping-storage:
    driver: local

networks:
  default:
    external:
      name: OMS
