FROM node:8

RUN npm install -g supervisor bunyan

RUN mkdir -p /usr/src/shared
WORKDIR /usr/src/app

RUN git clone https://github.com/AEGEE/oms-serviceregistry.git /usr/src/app \
	&& npm install

ADD https://raw.githubusercontent.com/AEGEE/oms-docker/stabilize/docker/docker-compose-staging.yml /usr/src/docker-compose.yml

CMD supervisor -e 'node,js,json' /usr/src/app/index.js | bunyan
