version: "3.4"

services:
  # minio:
  #   image: minio/minio:RELEASE.2020-04-15T19-42-18Z
  #   volumes:
  #     - minio_data:/export
  #   expose:
  #     - "9000"
  #   command: server /export
  #   environment:
  #     MINIO_ACCESS_KEY: AKIAIOSFODNN7ROFLCOPTER
  #     MINIO_SECRET_KEY: wJalrXUtnFEMI/K7MDENG/bPxRfiCYROFLCOPTER
  #   healthcheck:
  #     test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
  #     interval: 30s
  #     timeout: 20s
  #     retries: 3
  #   labels:
  #     - "traefik.backend=minio"
  #     - "traefik.port=9000"
  #     - "traefik.frontend.rule=Host:${SUBDOMAIN_STORAGE}${BASE_URL};PathPrefix:/"
  #     - "traefik.frontend.priority=110"
  #     - "traefik.enable=true"

  # postgres_nextcloud:
  #   image: postgres:10
  #   restart: always
  #   volumes:
  #     - postgres_nextcloud:/var/lib/mysql
  #   environment:
  #     POSTGRES_USER: "oc_${NEXTCLOUD_USERNAME}"
  #     POSTGRES_PASSWORD: ${PW_POSTGRES}
  #     POSTGRES_DB: nextcloud

  nextcloud:
    image: nextcloud:fpm-alpine
    # depends_on:
    #   - postgres_nextcloud
    volumes:
      - nextcloud:/var/www/html
    restart: always
    # environment:
    #   POSTGRES_HOST: postgres_nextcloud
    #   POSTGRES_USER: ${NEXTCLOUD_USERNAME}
    #   POSTGRES_PASSWORD: ${PW_POSTGRES}
    #   POSTGRES_DB: nextcloud
    #   NEXTCLOUD_ADMIN_USER: ${NEXTCLOUD_USERNAME}
    #   NEXTCLOUD_ADMIN_PASSWORD: ${NEXTCLOUD_PASSWORD}
      # SMTP_HOST: ${SENDGRID_SMTP_HOST}
      # SMTP_SECURE: "tls"
      # SMTP_PORT: "587"
      # SMTP_NAME: ${SENDGRID_USER}
      # SMTP_PASSWORD: ${SENDGRID_PW}
      # MAIL_FROM_ADDRESS: aegeefiles@${EMAIL_DOMAIN}
      # MAIL_DOMAIN: ${EMAIL_DOMAIN}
    # labels:
    #   - "traefik.backend=nextcloud"
    #   - "traefik.port=80"
    #   - "traefik.frontend.rule=Host:dl.${BASE_URL};PathPrefix:/"
    #   - "traefik.frontend.priority=110"
    #   - "traefik.enable=true"

  nginx_nextcloud:
    image: nginx:1.17.10-alpine
    restart: always
    expose:
      - "80"
    depends_on:
      - nextcloud
    volumes:
      - "./${PATH_OMS_STORAGE}/nextcloud-nginx.conf:/etc/nginx/nginx.conf:ro"
      - nextcloud:/var/www/html
    labels:
      - "traefik.backend=nginx_nextcloud"
      - "traefik.port=80"
      - "traefik.frontend.rule=Host:dl.${BASE_URL};PathPrefix:/"
      - "traefik.frontend.priority=110"
      - "traefik.enable=true"

  # firefoxsend:
  #   image: mozilla/send:latest
  #   links:
  #     - redis
  #   expose:
  #     - "1443"
  #   environment:
  #     REDIS_HOST: "redis_firefoxsend"
  #     #S3_BUCKET:
  #     MAX_FILE_SIZE: "512000000"

  # redis_firefoxsend:
  #   image: redis:alpine

volumes:
  minio1_data:
    driver: local
  postgres_nextcloud:
    driver: local
  nextcloud:
    driver: local

networks:
  default:
    external:
      name: OMS
