FROM node:8

RUN npm install -g --silent supervisor bunyan && \
	npm cache clean --force

RUN mkdir -p /usr/src/shared

RUN mkdir -p /usr/app/ \
        && mkdir -p /usr/app/media \
        && mkdir -p /usr/scripts \
        && mkdir -p /usr/shared \
        && mkdir -p /usr/app/oms-events

WORKDIR /usr/app/oms-events

ADD ./configFile.json /usr/scripts/configFile.json

CMD cp /usr/scripts/configFile.json lib/config/configFile.json && \
	npm install --silent && \
	supervisor -e 'node,js,json' lib/server.js | bunyan

EXPOSE 8082
