FROM node:8

RUN mkdir -p /usr/app/src \
	&& mkdir -p /usr/app/media \
	&& mkdir -p /usr/app/scripts

ADD ./bootstrap.sh /usr/app/scripts/bootstrap.sh

RUN chown -R node:node /usr/app

WORKDIR /usr/app/src

USER node

ENV NPM_CONFIG_PREFIX=/home/node/.npm-global

RUN npm install -g --loglevel warn pm2 bunyan && \
	npm cache clean --force


CMD sh /usr/app/scripts/bootstrap.sh && \
	/home/node/.npm-global/bin/pm2 start pm2config.json && \
	/home/node/.npm-global/bin/pm2 logs --raw | /home/node/.npm-global/bin/bunyan

EXPOSE 8082
