version: "3.4"

services:

### container administration helper Container #######################################
  # to get the password (hashed): (also remember to escape $ with anotehr $)
  #   docker run --rm httpd:2.4-alpine htpasswd -nbB admin 5ecr3t | cut -d ":" -f 2
  portainer:
    restart: "no"
    image: portainer/portainer:1.22.1
    # image: portainer/portainer:1.15.5 #they broke the tag
    command: -H unix:///var/run/docker.sock --admin-password ${PW_TRAEFIK} --logo ${AEGEE_LOGO_B64}  # yamllint disable-line rule:line-length
    expose:
      - "9000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:rw
    labels:
      - "traefik.enable=true"
      - "traefik.backend=portainer"
      - "traefik.port=9000"
      - "traefik.frontend.rule=Host:${SUBDOMAIN_PORTAINER}${BASE_URL}"
      - "traefik.frontend.priority=20"

### DB admin (UIs) Containers #######################################

### pgAdmin Container #######################################
  pgadmin:
    image: fenglc/pgadmin4:2.0
    restart: on-failure
    expose:
      - "5050"
    labels:
      - "traefik.enable=true"
      - "traefik.backend=pgadmin"
      - "traefik.port=5050"
      - "traefik.frontend.rule=Host:${SUBDOMAIN_PGADMIN}${BASE_URL}"
      - "traefik.frontend.priority=20"
      - "traefik.frontend.auth.basic.users=admin:${PW_TRAEFIK}"
    environment:
      DEFAULT_USER: "myaegee-admins@${EMAIL_DOMAIN}"
      DEFAULT_PASSWORD: "${PW_PGADMIN}"

  redisadmin:
    image: erikdubbelboer/phpredisadmin:v1.11.4
    environment:
      ADMIN_USER: admin
      ADMIN_PASS: ${PW_TRAEFIK}
      REDIS_1_HOST: redis-oms-gsuite-wrapper
      REDIS_1_PORT: 6379
    labels:
      - "traefik.enable=true"
      - "traefik.backend=redisadmin"
      - "traefik.port=80"
      - "traefik.frontend.rule=Host:${SUBDOMAIN_REDISADMIN}${BASE_URL}"
      - "traefik.frontend.priority=20"
      - "traefik.frontend.auth.basic.users=admin:${PW_TRAEFIK}"


### show api docs Container #######################################
  # swagger:
  #   image: swaggerapi/swagger-ui
  #   environment:
  #     API_URL: http://oms-events/api-docs.json
  #   labels:
  #     - traefik.enable=true
  #     - traefik.backend=swagger
  #     - traefik.port=8080
  #     - traefik.frontend.rule=Host:${SUBDOMAIN_APIDOCS}${BASE_URL}
  #     - traefik.frontend.priority=20


networks:
  default:
    external:
      name: OMS
