version: "3.4"
### NETWORK     #######################################
services:
    postgres-network:
        restart: always
        image: postgres:10.18
        volumes:
            - postgres-network:/var/lib/postgresql/data
        expose:
            - "5432"
        environment:
            POSTGRES_USER: "postgres"
            POSTGRES_PASSWORD: "${PW_POSTGRES}"
        labels:
            # we don't access via traefik
            - "traefik.enable=false"

    network:
        restart: always
        image: aegee/network:latest
        volumes:
            - network-media:/usr/app/media
            - shared:/usr/app/shared:ro
        depends_on:
            - postgres-network
        expose:
            - "8084"
        environment:
            BUGSNAG_KEY: "${BUGSNAG_KEY_NETWORK}"
            PG_PASSWORD: "${PW_POSTGRES}"
            NODE_ENV: "${MYAEGEE_ENV}"
            HOST: "${SUBDOMAIN_FRONTEND}${BASE_URL}"
        healthcheck:
            test: ["CMD", "curl", "-f", "http://localhost:8084/healthcheck"]
            interval: 30s
            timeout: 10s
            retries: 3
            start_period: 40s
        # cpu_count: 1
        # mem_limit: 900m
        labels:
            - "traefik.enable=true"
            - "traefik.http.routers.network.entrypoints=websecure"
            - "traefik.http.routers.network.tls=true"
            - "traefik.http.routers.network.rule=Host(`${SUBDOMAIN_FRONTEND}${BASE_URL}`) && PathPrefix(`/api/network`)"

            - "traefik.http.routers.network.middlewares=network-stripprefix"
            - "traefik.http.middlewares.network-stripprefix.stripprefix.prefixes=/api/network"

            - "traefik.http.routers.network-metrics.rule=Host(`${SUBDOMAIN_FRONTEND}${BASE_URL}`) && PathPrefix(`/api/network/metrics`)"
            - "traefik.http.routers.network-metrics.middlewares=network-stripprefix, metricsauth"

volumes:
    postgres-network:
        driver: local
    network-media:
        driver: local
    shared:
        driver: local

networks:
    default:
        external:
            name: OMS
