{
 "title": "discounts main dashboard",
 "time": { "from": "now-30m", "to": "now" },
 "panels": [
  {
   "title": "codes by integration and claimage",
   "type": "graph",
   "gridPos": { "h": 12, "w": 19, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(discounts_codes_total) by (claimed, integration_name)",
     "legendFormat": "claimed={{claimed}} for {{integration_name}}"
    }
   ]
  },
  {
   "title": "codes total",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 5, "x": 19, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    { "expr": "sum(discounts_codes_total)" }
   ]
  },
  {
   "title": "partners total",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 5, "x": 19, "y": 4 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    { "expr": "sum(discounts_partners_total)" }
   ]
  },
  {
   "title": "claimed total",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 5, "x": 19, "y": 8 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(discounts_codes_total{claimed=\"true\"})"
    }
   ]
  }
 ]
}