{
 "title": "events main dashboard",
 "time": { "from": "now-30m", "to": "now" },
 "panels": [
  {
   "title": "pax by event and type",
   "type": "graph",
   "gridPos": { "h": 12, "w": 19, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(events_applications_total) by (event_name)",
     "legendFormat": "{{ event_name }}"
    }
   ]
  },
  {
   "title": "applications total",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 5, "x": 19, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    { "expr": "sum(events_applications_total)" }
   ]
  },
  {
   "title": "events total",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 5, "x": 19, "y": 4 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    { "expr": "sum(events_events_total)" }
   ]
  },
  {
   "title": "events by type",
   "type": "graph",
   "gridPos": { "h": 9, "w": 13, "x": 0, "y": 12 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(events_events_total) by (type)",
     "legendFormat": "{{ type }}"
    }
   ]
  },
  {
   "title": "events by type and status",
   "type": "bargauge",
   "gridPos": { "h": 9, "w": 11, "x": 13, "y": 12 },
   "targets": [
    {
     "expr": "sum(events_events_total) by (type, status)",
     "legendFormat": "{{ status }} {{ type }}"
    }
   ]
  }
 ]
}