version: "3.4"

services:

### HTTP gateway    #######################################
### Proxy container #######################################

  traefik:
    image: traefik:v2.11.0
    restart: always
    ports:
      - 80:80
      - 443:443
      - 8080:8080
    healthcheck:
      test: wget --quiet --tries=1 --spider http://localhost:8080 || exit 1
      interval: 10s
      timeout: 10s
      retries: 3
      start_period: 10s
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      # below: we have to mount it to preserve it on the host, so no secrets
      - ./secrets/acme.json:/etc/acme.json
      - ./secrets/certs:/certs
      - ./${PATH_GATEWAYS}/traefik/cors.yml:/etc/traefik/cors.yml
      - ./${PATH_GATEWAYS}/traefik/logs:/var/log/
      # only for dev, but we keep it in this file for now
      - ./${PATH_GATEWAYS}/traefik/dynamic_conf_mkcert.yml:/etc/traefik/dynamic_conf_mkcert.yml
      # - shared_logs:/var/log/traefik/
#        networks:
#          - management
    command:
      - "--api.insecure=true"
      - "--api.dashboard=true"
      - "--metrics.prometheus=true"
      - "--metrics.prometheus.entrypoint=metrics"
      - "--log.level=INFO"
      - "--log.filePath=/var/log/traefik.log"
      - "--accesslog=true"
      - "--accesslog.filepath=/var/log/access.log"

      - "--providers.docker=true"
      - "--providers.docker.swarmMode=false"
      - "--providers.docker.exposedbydefault=false"
      - "--providers.docker.network=OMS"

      #for prometheus, http, https
      - "--entrypoints.metrics.address=:8082"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.web.http.redirections.entrypoint.to=websecure"
      - "--entrypoints.web.http.redirections.entrypoint.scheme=https"
      - "--entrypoints.websecure.address=:443"
      - "--entrypoints.websecure.http.tls=true"
      - "--entrypoints.websecure.http.tls.certResolver=myresolver"
      - "--entrypoints.websecure.http.tls.domains[0].main=${BASE_URL}"
      - "--entrypoints.websecure.http.tls.domains[0].sans=*.${BASE_URL}"

      #for CORS
      - "--providers.file.filename=/etc/traefik/cors.yml"

      #for HTTPS automatic
      - "--certificatesresolvers.myresolver.acme.httpchallenge.entrypoint=web"
      - "--certificatesresolvers.myresolver.acme.email=${DEVS_EMAIL}@aegee.eu"
      - "--certificatesresolvers.myresolver.acme.storage=acme.json"
      # For testing: staging certs of LE
      #- "--certificatesresolvers.myresolver.acme.caserver=https://acme-staging-v02.api.letsencrypt.org/directory"

      # Use the following line to configure Traefik to use the manually provided certificates
      # only for dev, but we keep it in this file for now
      - "--providers.file.filename=/etc/traefik/dynamic_conf_mkcert.yml" #FIXME see if it overrides cors.yml somehow

    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.api.entrypoints=websecure"
      - "traefik.http.routers.api.tls=true"
      - "traefik.http.routers.api.rule=Host(`${SUBDOMAIN_TRAEFIK}${BASE_URL}`)"
      - "traefik.http.routers.api.service=api@internal"

      - "traefik.http.routers.api.middlewares=traefikauth"
      - "traefik.http.middlewares.traefikauth.basicauth.users=admin:${PW_TRAEFIK}"

      # Defined here and used in all microservices
      - "traefik.http.middlewares.metricsauth.basicauth.users=admin:${METRICS_CREDENTIALS}"


# volumes:
#    shared_logs:
#        driver: "local"
#    upload:

networks:
  default:
    external:
      name: OMS
