version: "3.4"

services:

### HTTP gateway    #######################################
### Proxy container #######################################

  traefik:
    image: traefik:v1.7.4-alpine
    restart: always
    command: --web.metrics.prometheus
    #ports:
      #- 80:80
      #- 443:443
    healthcheck:
      test: ["CMD", "traefik", "healthcheck"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      # below: we have to mount it to preserve it on the host, so no secrets
      - ./secrets/acme.json:/etc/acme.json
      - ./${PATH_GATEWAYS}/traefik/traefik.toml:/etc/traefik/traefik.toml
      - ./${PATH_GATEWAYS}/traefik/logs:/var/log/traefik/
      # - shared_logs:/var/log/traefik/
#        networks:
#          - management
    labels:
      - traefik.enable=true
      - traefik.backend=traefik
      - traefik.port=8080
      - traefik.frontend.rule=Host:${SUBDOMAIN_TRAEFIK}${BASE_URL}
      - traefik.frontend.priority=20
      - traefik.frontend.auth.basic.users=admin:${PW_TRAEFIK}
# volumes:
#    shared_logs:
#        driver: "local"
#    upload:

  traefik2:
    # The official v2 Traefik docker image
    image: traefik:v2.2
    # Enables the web UI and tells Traefik to listen to docker
    command: --api.insecure=true --providers.docker
    ports:
      # The HTTP port
      - "80:80"
      # The Web UI (enabled by --api.insecure=true)
      - "8080:8080"
    volumes:
      # So that Traefik can listen to the Docker events
      - /var/run/docker.sock:/var/run/docker.sock
      - ./${PATH_GATEWAYS}/traefik/traefik2-providers.yaml:/etc/traefik/providers.yaml
    labels:
      - traefik.enable=true
      - traefik.backend=traefik2
      - traefik.port=8080
      - traefik.frontend.rule=Host:t${SUBDOMAIN_TRAEFIK}${BASE_URL}

  whoami:
    # A container that exposes an API to show its IP address
    image: containous/whoami
    labels:
      - "traefik.http.routers.whoami.rule=Host(`whoami.appserver.test`)"

networks:
  default:
    external:
      name: OMS
