FROM nginx:alpine

RUN adduser -D -H -u 1000 -s /bin/bash www-data \
	&& rm /etc/nginx/conf.d/default.conf 

RUN mkdir -p /usr/app/ \
        && mkdir -p /usr/app/frontend \
        && mkdir -p /usr/app/media \
        && mkdir -p /usr/scripts \
        && mkdir -p /usr/shared

WORKDIR /usr/app

ADD ./nginx.conf /etc/nginx/
COPY ./sites/*.conf /etc/nginx/sites-available/

CMD ["nginx"]

EXPOSE 8086
