version: "3.4"

services:

  postgres-mattermost:
    image: aegee/mattermost-db:5.21.0
    restart: unless-stopped
    volumes:
      - postgres_mattermost:/var/lib/postgresql/data
      - /etc/localtime:/etc/localtime:ro
    environment:
      POSTGRES_USER: "${MM_USERNAME}"
      PW_POSTGRES: "${PW_POSTGRES}"
      POSTGRES_DB: "mattermost"

  mattermost:
    image: aegee/mattermost-team:5.21.0
    restart: unless-stopped
    depends_on:
      - postgres-mattermost
    volumes:
      - mattermost_data:/mattermost
      - /etc/localtime:/etc/localtime:ro
    environment:
      MM_SERVICESETTINGS_SITEURL: "https://${SUBDOMAIN_CHAT}${BASE_URL}" #note:possibly not used?!
      MM_USERNAME: "${MM_USERNAME}"
      MM_PASSWORD: "${PW_POSTGRES}"
      MM_DBNAME: "mattermost"
      MM_SQLSETTINGS_DATASOURCE: "postgres://${MM_USERNAME}:${PW_POSTGRES}@postgres-mattermost:5432/mattermost?sslmode=disable&connect_timeout=10"
      #- MM_CONFIG=/mattermost/config/config.json # in case your config is not in default location
    labels:
      - "traefik.backend=mattermost"
      - "traefik.port=8000"
      - "traefik.frontend.rule=Host:${SUBDOMAIN_CHAT}${BASE_URL};PathPrefix:/"
      - "traefik.frontend.priority=110"
      - "traefik.enable=true"

volumes:
  postgres_mattermost:
    driver: local
  mattermost_data:
    driver: local

networks:
  default:
    external:
      name: OMS
