FROM nginx:1.15-alpine

RUN adduser -D -H -u 1000 -s /bin/bash www-data && rm /etc/nginx/conf.d/default.conf
RUN mkdir -p /usr/app/src/dist

WORKDIR /usr/app/src/dist

ADD ./nginx.conf /etc/nginx/
COPY ./sites/*.conf /etc/nginx/sites-available/

CMD ["nginx"]

EXPOSE 8083
