FROM nginx:alpine

RUN adduser -D -H -u 1000 -s /bin/bash www-data && rm /etc/nginx/conf.d/default.conf
WORKDIR /usr/app/src/dist

ADD ./nginx.conf /etc/nginx/
COPY ./sites/*.conf /etc/nginx/sites-available/

CMD ["nginx"]

EXPOSE 8083
